baseurl = "https://www.evdealkol.com/"
canonifyurls = true
copyright = "Copyright © 2019"
paginate = 4
theme = "swift"
title = "Evde Alkol"
[[menu.main]]
identifier = "blog"
name = "Üretim"
title = "blog section"
url = "/blog/"
weight = 1
[params]
description = "Evde alkol, meze ve ötesi"
staticman = false
[permalinks]
disqusShortname = "evdealkol"
post = "/:slug/"
