baseurl = "https://www.evdealkol.com/"
title = "Evde Alkol"
theme = "swift"
copyright = "Copyright © 2019"
canonifyurls = true
paginate = 4
[params]
  staticman = false
  description = "Evde alkol, meze ve ötesi"
  
  
[permalinks]
post = "/:slug/"

disqusShortname = "evdealkol"