baseurl = "https://www.evdealkol.com/"
title = "Evde Alkol"
theme = "swift"
copyright = "Copyright © 2019"
canonifyurls = true
paginate = 4
[params]
  staticman = false
  description = "Evde alkol, meze ve ötesi"
  
  
[permalinks]
post = "/:slug/"

disqusShortname = "evdealkol"


[menu]

  [[menu.main]]
    identifier = "blog"
    name = "This is the blog section"
    title = "blog section"
    url = "/blog/"
    weight = -110