baseurl = "https://www.evdealkol.com/"
canonifyurls = true
copyright = "Copyright © 2019"
paginate = 10
theme = "swift"
title = "Evde Alkol"
[[menu.main]]
name = "Gizlilik"
url = "https://evdealkol.com/gizlilik/"
weight = 2
[[menu.main]]
identifier = "blog"
name = "Üretim"
title = "blog section"
url = "/categories/uretim/"
weight = 1
[params]
description = "Evde alkol, meze ve ötesi"
staticman = false
[permalinks]
disqusShortname = "evdealkol"
post = "/:slug/"
